// <auto-generated />
using System;
using AMIS.Modules.ProcurementAcquisition.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace AMIS.Playground.Migrations.PostgreSQL.ProcurementAcquisition
{
    [DbContext(typeof(ProcurementDbContext))]
    [Migration("20260716120733_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("AMIS.Modules.ProcurementAcquisition.Domain.Canvass.CanvassQuotation", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("CanvassRequestId")
                        .HasColumnType("uuid");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("text");

                    b.Property<DateTimeOffset>("CreatedOnUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("DeletedBy")
                        .HasColumnType("text");

                    b.Property<DateTimeOffset?>("DeletedOnUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("DeliveryTerms")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<bool>("IsAwarded")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false);

                    b.Property<string>("LastModifiedBy")
                        .HasColumnType("text");

                    b.Property<DateTimeOffset?>("LastModifiedOnUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateOnly>("QuotationDate")
                        .HasColumnType("date");

                    b.Property<string>("SupplierAddress")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<Guid>("SupplierId")
                        .HasColumnType("uuid");

                    b.Property<string>("SupplierName")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("TenantId")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<string>("TinNumber")
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.HasKey("Id");

                    b.HasIndex("CanvassRequestId");

                    b.HasIndex("SupplierId");

                    b.ToTable("CanvassQuotations", "procurement");

                    b.HasAnnotation("Finbuckle:MultiTenant", true);
                });

            modelBuilder.Entity("AMIS.Modules.ProcurementAcquisition.Domain.Canvass.CanvassRequest", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid?>("AwardedSupplierId")
                        .HasColumnType("uuid");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("text");

                    b.Property<DateTimeOffset>("CreatedOnUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("DeletedBy")
                        .HasColumnType("text");

                    b.Property<DateTimeOffset?>("DeletedOnUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false);

                    b.Property<string>("LastModifiedBy")
                        .HasColumnType("text");

                    b.Property<DateTimeOffset?>("LastModifiedOnUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("PurchaseRequestId")
                        .HasColumnType("uuid");

                    b.Property<DateOnly>("ReturnDeadline")
                        .HasColumnType("date");

                    b.Property<string>("RivNumber")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<string>("TenantId")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<uint>("xmin")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid")
                        .HasColumnName("xmin");

                    b.HasKey("Id");

                    b.HasIndex("PurchaseRequestId");

                    b.HasIndex("TenantId", "RivNumber")
                        .IsUnique();

                    b.HasIndex("TenantId", "Status");

                    b.ToTable("CanvassRequests", "procurement");

                    b.HasAnnotation("Finbuckle:MultiTenant", true);
                });

            modelBuilder.Entity("AMIS.Modules.ProcurementAcquisition.Domain.Canvass.RivNumberSequence", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("LastSerial")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0);

                    b.Property<string>("TenantId")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<int>("Year")
                        .HasColumnType("integer");

                    b.Property<uint>("xmin")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid")
                        .HasColumnName("xmin");

                    b.HasKey("Id");

                    b.HasIndex("TenantId", "Year")
                        .IsUnique();

                    b.ToTable("RivNumberSequences", "procurement");

                    b.HasAnnotation("Finbuckle:MultiTenant", true);
                });

            modelBuilder.Entity("AMIS.Modules.ProcurementAcquisition.Domain.InspectionAcceptanceReports.IarNumberSequence", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("LastSerial")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0);

                    b.Property<string>("TenantId")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<int>("Year")
                        .HasColumnType("integer");

                    b.Property<uint>("xmin")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid")
                        .HasColumnName("xmin");

                    b.HasKey("Id");

                    b.HasIndex("TenantId", "Year")
                        .IsUnique();

                    b.ToTable("IarNumberSequences", "procurement");

                    b.HasAnnotation("Finbuckle:MultiTenant", true);
                });

            modelBuilder.Entity("AMIS.Modules.ProcurementAcquisition.Domain.InspectionAcceptanceReports.InspectionAcceptanceReport", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("AcceptedByDesignation")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<Guid?>("AcceptedById")
                        .HasColumnType("uuid");

                    b.Property<string>("AcceptedByName")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<DateTimeOffset?>("AcceptedOnUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset?>("CancelledOnUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Category")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0);

                    b.Property<string>("CreatedBy")
                        .HasColumnType("text");

                    b.Property<DateTimeOffset>("CreatedOnUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("DeletedBy")
                        .HasColumnType("text");

                    b.Property<DateTimeOffset?>("DeletedOnUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateOnly?>("DeliveryDate")
                        .HasColumnType("date");

                    b.Property<string>("DeliveryReceiptNo")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<DateOnly>("IarDate")
                        .HasColumnType("date");

                    b.Property<string>("IarNumber")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<Guid>("InspectedById")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset?>("InspectedOnUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<string>("LastModifiedBy")
                        .HasColumnType("text");

                    b.Property<DateTimeOffset?>("LastModifiedOnUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("PurchaseOrderId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("ReceivedById")
                        .HasColumnType("uuid");

                    b.Property<string>("Remarks")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset?>("SubmittedForInspectionOnUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("SupplierId")
                        .HasColumnType("uuid");

                    b.Property<string>("SupplierName")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("TenantId")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<uint>("xmin")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid")
                        .HasColumnName("xmin");

                    b.HasKey("Id");

                    b.HasIndex("CreatedOnUtc");

                    b.HasIndex("TenantId", "IarNumber")
                        .IsUnique();

                    b.HasIndex("TenantId", "PurchaseOrderId");

                    b.HasIndex("TenantId", "Status");

                    b.ToTable("InspectionAcceptanceReports", "procurement");

                    b.HasAnnotation("Finbuckle:MultiTenant", true);
                });

            modelBuilder.Entity("AMIS.Modules.ProcurementAcquisition.Domain.JobOrders.JoNumberSequence", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("LastSerial")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0);

                    b.Property<int>("Month")
                        .HasColumnType("integer");

                    b.Property<string>("TenantId")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<int>("Year")
                        .HasColumnType("integer");

                    b.Property<uint>("xmin")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid")
                        .HasColumnName("xmin");

                    b.HasKey("Id");

                    b.HasIndex("TenantId", "Year", "Month")
                        .IsUnique();

                    b.ToTable("JoNumberSequences", "procurement");

                    b.HasAnnotation("Finbuckle:MultiTenant", true);
                });

            modelBuilder.Entity("AMIS.Modules.ProcurementAcquisition.Domain.JobOrders.JobOrder", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("AcceptanceInvoiceNo")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<Guid?>("AcceptedById")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset?>("AcceptedOnUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("CancellationReason")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("text");

                    b.Property<DateTimeOffset>("CreatedOnUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateOnly?>("DateInspected")
                        .HasColumnType("date");

                    b.Property<DateOnly?>("DateOfDelivery")
                        .HasColumnType("date");

                    b.Property<DateOnly?>("DateReceived")
                        .HasColumnType("date");

                    b.Property<string>("DeletedBy")
                        .HasColumnType("text");

                    b.Property<DateTimeOffset?>("DeletedOnUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("DeliveryTerm")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<bool>("FoundInOrder")
                        .HasColumnType("boolean");

                    b.Property<string>("FundCluster")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("FundsAvailableCertifiedByDesignation")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<Guid?>("FundsAvailableCertifiedById")
                        .HasColumnType("uuid");

                    b.Property<string>("FundsAvailableCertifiedByName")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<DateTimeOffset?>("FundsAvailableCertifiedOnUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset?>("InspectedOnUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("InspectionFindings")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<DateOnly?>("InspectionInvoiceDate")
                        .HasColumnType("date");

                    b.Property<string>("InspectionInvoiceNo")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<string>("InspectorDesignation")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<Guid>("InspectorId")
                        .HasColumnType("uuid");

                    b.Property<string>("InspectorName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<bool>("IsCompleteDelivery")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false);

                    b.Property<string>("IssuedByDesignation")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<Guid?>("IssuedById")
                        .HasColumnType("uuid");

                    b.Property<string>("IssuedByName")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<DateTimeOffset?>("IssuedOnUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateOnly>("JoDate")
                        .HasColumnType("date");

                    b.Property<string>("JoNumber")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<string>("JobRequestNo")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<string>("LastModifiedBy")
                        .HasColumnType("text");

                    b.Property<DateTimeOffset?>("LastModifiedOnUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("ModeOfProcurement")
                        .HasColumnType("integer");

                    b.Property<DateOnly?>("OursBursDate")
                        .HasColumnType("date");

                    b.Property<string>("OursBursNumber")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("PartialDeliveryNote")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("PaymentTerm")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("PlaceOfDelivery")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<Guid?>("PurchaseRequestId")
                        .HasColumnType("uuid");

                    b.Property<string>("RequisitioningOffice")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<string>("SupplierAddress")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<Guid>("SupplierId")
                        .HasColumnType("uuid");

                    b.Property<string>("SupplierName")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("SupplierTin")
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<string>("TenantId")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<uint>("xmin")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid")
                        .HasColumnName("xmin");

                    b.HasKey("Id");

                    b.HasIndex("PurchaseRequestId");

                    b.HasIndex("TenantId", "JoNumber")
                        .IsUnique();

                    b.HasIndex("TenantId", "Status");

                    b.ToTable("JobOrders", "procurement");

                    b.HasAnnotation("Finbuckle:MultiTenant", true);
                });

            modelBuilder.Entity("AMIS.Modules.ProcurementAcquisition.Domain.PurchaseOrders.PoNumberSequence", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("LastSerial")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0);

                    b.Property<int>("Month")
                        .HasColumnType("integer");

                    b.Property<string>("TenantId")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<int>("Year")
                        .HasColumnType("integer");

                    b.Property<uint>("xmin")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid")
                        .HasColumnName("xmin");

                    b.HasKey("Id");

                    b.HasIndex("TenantId", "Year", "Month")
                        .IsUnique();

                    b.ToTable("PoNumberSequences", "procurement");

                    b.HasAnnotation("Finbuckle:MultiTenant", true);
                });

            modelBuilder.Entity("AMIS.Modules.ProcurementAcquisition.Domain.PurchaseOrders.PurchaseOrder", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("CancellationReason")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<Guid?>("CanvassRequestId")
                        .HasColumnType("uuid");

                    b.Property<int>("Category")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0);

                    b.Property<string>("CreatedBy")
                        .HasColumnType("text");

                    b.Property<DateTimeOffset>("CreatedOnUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateOnly?>("DateOfDelivery")
                        .HasColumnType("date");

                    b.Property<string>("DeletedBy")
                        .HasColumnType("text");

                    b.Property<DateTimeOffset?>("DeletedOnUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("DeliveryTerm")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("FundCluster")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("FundsAvailableCertifiedByDesignation")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<Guid?>("FundsAvailableCertifiedById")
                        .HasColumnType("uuid");

                    b.Property<string>("FundsAvailableCertifiedByName")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<DateTimeOffset?>("FundsAvailableCertifiedOnUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false);

                    b.Property<string>("IssuedByDesignation")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<Guid?>("IssuedById")
                        .HasColumnType("uuid");

                    b.Property<string>("IssuedByName")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<DateTimeOffset?>("IssuedOnUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("LastModifiedBy")
                        .HasColumnType("text");

                    b.Property<DateTimeOffset?>("LastModifiedOnUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("ModeOfProcurement")
                        .HasColumnType("integer");

                    b.Property<DateOnly?>("OursBursDate")
                        .HasColumnType("date");

                    b.Property<string>("OursBursNumber")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("PaymentTerm")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("PlaceOfDelivery")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<DateOnly>("PoDate")
                        .HasColumnType("date");

                    b.Property<string>("PoNumber")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<Guid>("PurchaseRequestId")
                        .HasColumnType("uuid");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<string>("SupplierAddress")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<Guid>("SupplierId")
                        .HasColumnType("uuid");

                    b.Property<string>("SupplierName")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("SupplierTin")
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<string>("TenantId")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<uint>("xmin")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid")
                        .HasColumnName("xmin");

                    b.HasKey("Id");

                    b.HasIndex("PurchaseRequestId");

                    b.HasIndex("TenantId", "PoNumber")
                        .IsUnique();

                    b.HasIndex("TenantId", "Status");

                    b.ToTable("PurchaseOrders", "procurement");

                    b.HasAnnotation("Finbuckle:MultiTenant", true);
                });

            modelBuilder.Entity("AMIS.Modules.ProcurementAcquisition.Domain.PurchaseRequests.PrNumberSequence", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("LastSerial")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0);

                    b.Property<string>("TenantId")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<int>("Year")
                        .HasColumnType("integer");

                    b.Property<uint>("xmin")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid")
                        .HasColumnName("xmin");

                    b.HasKey("Id");

                    b.HasIndex("TenantId", "Year")
                        .IsUnique();

                    b.ToTable("PrNumberSequences", "procurement");

                    b.HasAnnotation("Finbuckle:MultiTenant", true);
                });

            modelBuilder.Entity("AMIS.Modules.ProcurementAcquisition.Domain.PurchaseRequests.PurchaseRequest", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateOnly?>("AlobsDate")
                        .HasColumnType("date");

                    b.Property<string>("AlobsNumber")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<string>("ApprovedByDesignation")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<Guid?>("ApprovedById")
                        .HasColumnType("uuid");

                    b.Property<string>("ApprovedByName")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<DateTimeOffset?>("ApprovedOnUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("CancellationReason")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<int>("Category")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0);

                    b.Property<string>("CreatedBy")
                        .HasColumnType("text");

                    b.Property<DateTimeOffset>("CreatedOnUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("DeletedBy")
                        .HasColumnType("text");

                    b.Property<DateTimeOffset?>("DeletedOnUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("DepartmentId")
                        .HasColumnType("uuid");

                    b.Property<string>("FundsAvailableCertifiedByDesignation")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<Guid?>("FundsAvailableCertifiedById")
                        .HasColumnType("uuid");

                    b.Property<string>("FundsAvailableCertifiedByName")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<DateTimeOffset?>("FundsAvailableCertifiedOnUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false);

                    b.Property<string>("Justification")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<string>("LastModifiedBy")
                        .HasColumnType("text");

                    b.Property<DateTimeOffset?>("LastModifiedOnUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateOnly>("PrDate")
                        .HasColumnType("date");

                    b.Property<string>("PrNumber")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<int>("PrType")
                        .HasColumnType("integer");

                    b.Property<string>("Purpose")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("RejectionReason")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<string>("RequestedByDesignation")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<Guid?>("RequestedById")
                        .HasColumnType("uuid");

                    b.Property<string>("RequestedByName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("ResponsibilityCenterCode")
                        .HasMaxLength(160)
                        .HasColumnType("character varying(160)");

                    b.Property<Guid?>("ReturnedById")
                        .HasColumnType("uuid");

                    b.Property<string>("ReturnedByName")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<DateTimeOffset?>("ReturnedOnUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("ReturnedReason")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<DateOnly?>("SaiDate")
                        .HasColumnType("date");

                    b.Property<string>("SaiNumber")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<string>("TenantId")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<uint>("xmin")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid")
                        .HasColumnName("xmin");

                    b.HasKey("Id");

                    b.HasIndex("TenantId", "DepartmentId");

                    b.HasIndex("TenantId", "PrNumber")
                        .IsUnique();

                    b.HasIndex("TenantId", "Status");

                    b.ToTable("PurchaseRequests", "procurement");

                    b.HasAnnotation("Finbuckle:MultiTenant", true);
                });

            modelBuilder.Entity("AMIS.Modules.ProcurementAcquisition.Domain.SignedDocuments.SignedDocument", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("ContentType")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("text");

                    b.Property<DateTimeOffset>("CreatedOnUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("DeletedBy")
                        .HasColumnType("text");

                    b.Property<DateTimeOffset?>("DeletedOnUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("DocumentId")
                        .HasColumnType("uuid");

                    b.Property<int>("DocumentType")
                        .HasColumnType("integer");

                    b.Property<string>("FileName")
                        .IsRequired()
                        .HasMaxLength(260)
                        .HasColumnType("character varying(260)");

                    b.Property<long>("FileSizeBytes")
                        .HasColumnType("bigint");

                    b.Property<bool>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false);

                    b.Property<string>("LastModifiedBy")
                        .HasColumnType("text");

                    b.Property<DateTimeOffset?>("LastModifiedOnUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Sha256")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<string>("StorageKey")
                        .IsRequired()
                        .HasMaxLength(1024)
                        .HasColumnType("character varying(1024)");

                    b.Property<string>("TenantId")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<Guid?>("UploadedById")
                        .HasColumnType("uuid");

                    b.Property<string>("UploadedByName")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<DateTimeOffset>("UploadedOnUtc")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("TenantId", "DocumentType", "DocumentId")
                        .IsUnique();

                    b.ToTable("SignedDocuments", "procurement");

                    b.HasAnnotation("Finbuckle:MultiTenant", true);
                });

            modelBuilder.Entity("AMIS.Modules.ProcurementAcquisition.Domain.Canvass.CanvassQuotation", b =>
                {
                    b.HasOne("AMIS.Modules.ProcurementAcquisition.Domain.Canvass.CanvassRequest", null)
                        .WithMany("Quotations")
                        .HasForeignKey("CanvassRequestId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.OwnsMany("AMIS.Modules.ProcurementAcquisition.Domain.Canvass.CanvassQuotationLineItem", "LineItems", b1 =>
                        {
                            b1.Property<Guid>("CanvassQuotationId");

                            b1.Property<int>("__synthesizedOrdinal")
                                .ValueGeneratedOnAdd();

                            b1.Property<string>("Description")
                                .IsRequired()
                                .HasMaxLength(500);

                            b1.Property<int>("ItemNo");

                            b1.Property<int>("PrItemNo");

                            b1.Property<decimal>("Quantity")
                                .HasPrecision(18, 4);

                            b1.Property<string>("Unit")
                                .IsRequired()
                                .HasMaxLength(64);

                            b1.Property<decimal>("UnitPrice")
                                .HasPrecision(18, 4);

                            b1.HasKey("CanvassQuotationId", "__synthesizedOrdinal");

                            b1.ToTable("CanvassQuotations", "procurement");

                            b1
                                .ToJson("LineItems")
                                .HasColumnType("jsonb");

                            b1.WithOwner()
                                .HasForeignKey("CanvassQuotationId");
                        });

                    b.Navigation("LineItems");
                });

            modelBuilder.Entity("AMIS.Modules.ProcurementAcquisition.Domain.Canvass.CanvassRequest", b =>
                {
                    b.OwnsMany("AMIS.Modules.ProcurementAcquisition.Domain.Canvass.CanvassAwardSignatory", "AwardSignatories", b1 =>
                        {
                            b1.Property<Guid>("CanvassRequestId");

                            b1.Property<int>("__synthesizedOrdinal")
                                .ValueGeneratedOnAdd();

                            b1.Property<string>("Name")
                                .IsRequired()
                                .HasMaxLength(200);

                            b1.Property<string>("Role")
                                .IsRequired()
                                .HasMaxLength(200);

                            b1.Property<int>("SortOrder");

                            b1.HasKey("CanvassRequestId", "__synthesizedOrdinal");

                            b1.ToTable("CanvassRequests", "procurement");

                            b1
                                .ToJson("AwardSignatories")
                                .HasColumnType("jsonb");

                            b1.WithOwner()
                                .HasForeignKey("CanvassRequestId");
                        });

                    b.OwnsMany("AMIS.Modules.ProcurementAcquisition.Domain.Canvass.CanvassRequestLineItem", "LineItems", b1 =>
                        {
                            b1.Property<Guid>("CanvassRequestId");

                            b1.Property<int>("__synthesizedOrdinal")
                                .ValueGeneratedOnAdd();

                            b1.Property<Guid?>("AwardedQuotationId");

                            b1.Property<Guid?>("AwardedSupplierId");

                            b1.Property<decimal?>("AwardedUnitPrice")
                                .HasPrecision(18, 4);

                            b1.Property<Guid?>("CatalogItemId");

                            b1.Property<string>("Description")
                                .IsRequired()
                                .HasMaxLength(500);

                            b1.Property<decimal>("EstimatedUnitCost")
                                .HasPrecision(18, 4);

                            b1.Property<int>("PrItemNo");

                            b1.Property<decimal>("Quantity")
                                .HasPrecision(18, 4);

                            b1.Property<string>("UacsObjectCode")
                                .HasMaxLength(64);

                            b1.Property<string>("Unit")
                                .IsRequired()
                                .HasMaxLength(64);

                            b1.HasKey("CanvassRequestId", "__synthesizedOrdinal");

                            b1.ToTable("CanvassRequests", "procurement");

                            b1
                                .ToJson("LineItems")
                                .HasColumnType("jsonb");

                            b1.WithOwner()
                                .HasForeignKey("CanvassRequestId");
                        });

                    b.Navigation("AwardSignatories");

                    b.Navigation("LineItems");
                });

            modelBuilder.Entity("AMIS.Modules.ProcurementAcquisition.Domain.InspectionAcceptanceReports.InspectionAcceptanceReport", b =>
                {
                    b.OwnsMany("AMIS.Modules.ProcurementAcquisition.Domain.InspectionAcceptanceReports.InspectionAcceptanceReportLineItem", "LineItems", b1 =>
                        {
                            b1.Property<Guid>("InspectionAcceptanceReportId");

                            b1.Property<int>("__synthesizedOrdinal")
                                .ValueGeneratedOnAdd();

                            b1.Property<string>("Brand")
                                .HasMaxLength(200);

                            b1.Property<Guid?>("CatalogItemId");

                            b1.Property<string>("Description")
                                .IsRequired()
                                .HasMaxLength(500);

                            b1.Property<Guid?>("InspectedById");

                            b1.Property<DateTimeOffset?>("InspectedOnUtc");

                            b1.Property<string>("InspectionRemarks")
                                .HasMaxLength(500);

                            b1.Property<int>("InspectionResult");

                            b1.Property<int>("ItemNo");

                            b1.Property<string>("Model")
                                .HasMaxLength(200);

                            b1.Property<string>("PropertyClassHint")
                                .HasMaxLength(64);

                            b1.Property<decimal>("Quantity");

                            b1.Property<string>("SerialNo")
                                .HasMaxLength(200);

                            b1.Property<string>("StockNumber")
                                .HasMaxLength(64);

                            b1.Property<string>("StockPropertyNo")
                                .HasMaxLength(64);

                            b1.Property<string>("TechnicalSpecifications")
                                .HasMaxLength(1000);

                            b1.Property<string>("UacsObjectCode")
                                .HasMaxLength(64);

                            b1.Property<string>("Unit")
                                .IsRequired()
                                .HasMaxLength(64);

                            b1.Property<decimal>("UnitCost");

                            b1.HasKey("InspectionAcceptanceReportId", "__synthesizedOrdinal");

                            b1.ToTable("InspectionAcceptanceReports", "procurement");

                            b1
                                .ToJson("LineItems")
                                .HasColumnType("jsonb");

                            b1.WithOwner()
                                .HasForeignKey("InspectionAcceptanceReportId");
                        });

                    b.Navigation("LineItems");
                });

            modelBuilder.Entity("AMIS.Modules.ProcurementAcquisition.Domain.JobOrders.JobOrder", b =>
                {
                    b.OwnsMany("AMIS.Modules.ProcurementAcquisition.Domain.JobOrders.JobOrderLineItem", "LineItems", b1 =>
                        {
                            b1.Property<Guid>("JobOrderId");

                            b1.Property<int>("__synthesizedOrdinal")
                                .ValueGeneratedOnAdd();

                            b1.Property<string>("Description")
                                .IsRequired()
                                .HasMaxLength(500);

                            b1.Property<int>("ItemNo");

                            b1.Property<decimal>("Quantity")
                                .HasPrecision(18, 4);

                            b1.Property<string>("Unit")
                                .HasMaxLength(64);

                            b1.Property<decimal>("UnitCost")
                                .HasPrecision(18, 4);

                            b1.HasKey("JobOrderId", "__synthesizedOrdinal");

                            b1.ToTable("JobOrders", "procurement");

                            b1
                                .ToJson("LineItems")
                                .HasColumnType("jsonb");

                            b1.WithOwner()
                                .HasForeignKey("JobOrderId");
                        });

                    b.Navigation("LineItems");
                });

            modelBuilder.Entity("AMIS.Modules.ProcurementAcquisition.Domain.PurchaseOrders.PurchaseOrder", b =>
                {
                    b.OwnsMany("AMIS.Modules.ProcurementAcquisition.Domain.PurchaseOrders.PurchaseOrderLineItem", "LineItems", b1 =>
                        {
                            b1.Property<Guid>("PurchaseOrderId");

                            b1.Property<int>("__synthesizedOrdinal")
                                .ValueGeneratedOnAdd();

                            b1.Property<Guid?>("CatalogItemId");

                            b1.Property<string>("Description")
                                .IsRequired()
                                .HasMaxLength(500);

                            b1.Property<int>("ItemNo");

                            b1.Property<decimal>("Quantity")
                                .HasPrecision(18, 4);

                            b1.Property<string>("StockNumber")
                                .HasMaxLength(64);

                            b1.Property<string>("Unit")
                                .IsRequired()
                                .HasMaxLength(64);

                            b1.Property<decimal>("UnitCost")
                                .HasPrecision(18, 4);

                            b1.HasKey("PurchaseOrderId", "__synthesizedOrdinal");

                            b1.ToTable("PurchaseOrders", "procurement");

                            b1
                                .ToJson("LineItems")
                                .HasColumnType("jsonb");

                            b1.WithOwner()
                                .HasForeignKey("PurchaseOrderId");
                        });

                    b.Navigation("LineItems");
                });

            modelBuilder.Entity("AMIS.Modules.ProcurementAcquisition.Domain.PurchaseRequests.PurchaseRequest", b =>
                {
                    b.OwnsMany("AMIS.Modules.ProcurementAcquisition.Domain.PurchaseRequests.PurchaseRequestLineItem", "LineItems", b1 =>
                        {
                            b1.Property<Guid>("PurchaseRequestId");

                            b1.Property<int>("__synthesizedOrdinal")
                                .ValueGeneratedOnAdd();

                            b1.Property<Guid?>("CatalogItemId");

                            b1.Property<decimal>("EstimatedUnitCost")
                                .HasPrecision(18, 4);

                            b1.Property<string>("ItemDescription")
                                .IsRequired()
                                .HasMaxLength(500);

                            b1.Property<int>("ItemNo");

                            b1.Property<decimal>("Quantity")
                                .HasPrecision(18, 4);

                            b1.Property<string>("StockNumber")
                                .HasMaxLength(64);

                            b1.Property<string>("UacsObjectCode")
                                .HasMaxLength(64);

                            b1.Property<string>("UnitOfIssue")
                                .IsRequired()
                                .HasMaxLength(64);

                            b1.HasKey("PurchaseRequestId", "__synthesizedOrdinal");

                            b1.ToTable("PurchaseRequests", "procurement");

                            b1
                                .ToJson("LineItems")
                                .HasColumnType("jsonb");

                            b1.WithOwner()
                                .HasForeignKey("PurchaseRequestId");
                        });

                    b.Navigation("LineItems");
                });

            modelBuilder.Entity("AMIS.Modules.ProcurementAcquisition.Domain.Canvass.CanvassRequest", b =>
                {
                    b.Navigation("Quotations");
                });
#pragma warning restore 612, 618
        }
    }
}
