<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<RootNamespace>AMIS.Modules.QuestPdfReporting.Contracts</RootNamespace>
		<AssemblyName>AMIS.Modules.QuestPdfReporting.Contracts</AssemblyName>
		<PackageId>AMIS.Modules.QuestPdfReporting.Contracts</PackageId>
		<NoWarn>$(NoWarn);CA1002;CA1056;CS1572;S2094</NoWarn>
	</PropertyGroup>

	<ItemGroup>
		<PackageReference Include="Mediator.Abstractions" />
	</ItemGroup>

	<ItemGroup>
		<ProjectReference Include="..\..\..\BuildingBlocks\Shared\Shared.csproj" />
	</ItemGroup>

</Project>
