// <auto-generated />
using System;
using AMIS.Modules.AssetProcurement.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace AMIS.Playground.Migrations.PostgreSQL.Procurement
{
    [DbContext(typeof(AssetProcurementDbContext))]
    [Migration("20260515013234_IAR_DropRejectionReason")]
    partial class IAR_DropRejectionReason
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("AMIS.Modules.AssetProcurement.Domain.AssetInspectionAcceptanceReports.AssetInspectionAcceptanceReport", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset?>("AcceptedOnUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset?>("CancelledOnUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("text");

                    b.Property<DateTimeOffset>("CreatedOnUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("DeletedBy")
                        .HasColumnType("text");

                    b.Property<DateTimeOffset?>("DeletedOnUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateOnly?>("DeliveryDate")
                        .HasColumnType("date");

                    b.Property<string>("DeliveryReceiptNo")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<DateOnly>("IarDate")
                        .HasColumnType("date");

                    b.Property<string>("IarNumber")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<Guid>("InspectedById")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset?>("InspectedOnUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<string>("LastModifiedBy")
                        .HasColumnType("text");

                    b.Property<DateTimeOffset?>("LastModifiedOnUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("PurchaseOrderId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("ReceivedById")
                        .HasColumnType("uuid");

                    b.Property<string>("Remarks")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset?>("SubmittedForInspectionOnUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("SupplierId")
                        .HasColumnType("uuid");

                    b.Property<string>("SupplierName")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("TenantId")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<byte[]>("Version")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("bytea");

                    b.HasKey("Id");

                    b.HasIndex("CreatedOnUtc");

                    b.HasIndex("TenantId", "IarNumber")
                        .IsUnique();

                    b.HasIndex("TenantId", "PurchaseOrderId");

                    b.HasIndex("TenantId", "Status");

                    b.ToTable("AssetIARs", "asset_procurement");

                    b.HasAnnotation("Finbuckle:MultiTenant", true);
                });

            modelBuilder.Entity("AMIS.Modules.AssetProcurement.Domain.AssetPurchaseOrders.AssetPurchaseOrder", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("CancellationReason")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("text");

                    b.Property<DateTimeOffset>("CreatedOnUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateOnly?>("DateOfDelivery")
                        .HasColumnType("date");

                    b.Property<string>("DeletedBy")
                        .HasColumnType("text");

                    b.Property<DateTimeOffset?>("DeletedOnUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("DeliveryTerm")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("FundCluster")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<string>("LastModifiedBy")
                        .HasColumnType("text");

                    b.Property<DateTimeOffset?>("LastModifiedOnUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("ModeOfProcurement")
                        .HasColumnType("integer");

                    b.Property<string>("OblRequestNumber")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<string>("PaymentTerm")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("PlaceOfDelivery")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<DateOnly>("PoDate")
                        .HasColumnType("date");

                    b.Property<string>("PoNumber")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<Guid>("PurchaseRequestId")
                        .HasColumnType("uuid");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<string>("SupplierAddress")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<Guid>("SupplierId")
                        .HasColumnType("uuid");

                    b.Property<string>("SupplierName")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("SupplierTin")
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<string>("TenantId")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<byte[]>("Version")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("bytea");

                    b.HasKey("Id");

                    b.HasIndex("CreatedOnUtc");

                    b.HasIndex("TenantId", "PoNumber")
                        .IsUnique();

                    b.HasIndex("TenantId", "PurchaseRequestId");

                    b.HasIndex("TenantId", "Status");

                    b.ToTable("AssetPurchaseOrders", "asset_procurement");

                    b.HasAnnotation("Finbuckle:MultiTenant", true);
                });

            modelBuilder.Entity("AMIS.Modules.AssetProcurement.Domain.AssetPurchaseRequests.AssetPurchaseRequest", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateOnly?>("AlobsDate")
                        .HasColumnType("date");

                    b.Property<string>("AlobsNumber")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<Guid?>("ApprovedById")
                        .HasColumnType("uuid");

                    b.Property<string>("CancellationReason")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("text");

                    b.Property<DateTimeOffset>("CreatedOnUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("DeletedBy")
                        .HasColumnType("text");

                    b.Property<DateTimeOffset?>("DeletedOnUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("DepartmentId")
                        .HasColumnType("uuid");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<string>("Justification")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<string>("LastModifiedBy")
                        .HasColumnType("text");

                    b.Property<DateTimeOffset?>("LastModifiedOnUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateOnly>("PrDate")
                        .HasColumnType("date");

                    b.Property<string>("PrNumber")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<int>("PrType")
                        .HasColumnType("integer");

                    b.Property<string>("Purpose")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("RejectionReason")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<Guid>("RequestedById")
                        .HasColumnType("uuid");

                    b.Property<DateOnly?>("SaiDate")
                        .HasColumnType("date");

                    b.Property<string>("SaiNumber")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<string>("Section")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<string>("TenantId")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<byte[]>("Version")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("bytea");

                    b.HasKey("Id");

                    b.HasIndex("CreatedOnUtc");

                    b.HasIndex("TenantId", "DepartmentId");

                    b.HasIndex("TenantId", "PrNumber")
                        .IsUnique();

                    b.HasIndex("TenantId", "Status");

                    b.ToTable("AssetPurchaseRequests", "asset_procurement");

                    b.HasAnnotation("Finbuckle:MultiTenant", true);
                });

            modelBuilder.Entity("AMIS.Modules.AssetProcurement.Domain.AssetInspectionAcceptanceReports.AssetInspectionAcceptanceReport", b =>
                {
                    b.OwnsMany("AMIS.Modules.AssetProcurement.Domain.AssetInspectionAcceptanceReports.AssetIARLineItem", "LineItems", b1 =>
                        {
                            b1.Property<Guid>("AssetInspectionAcceptanceReportId");

                            b1.Property<int>("__synthesizedOrdinal")
                                .ValueGeneratedOnAdd();

                            b1.Property<string>("Brand")
                                .HasMaxLength(200);

                            b1.Property<string>("Description")
                                .IsRequired()
                                .HasMaxLength(500);

                            b1.Property<Guid?>("InspectedById");

                            b1.Property<DateTimeOffset?>("InspectedOnUtc");

                            b1.Property<string>("InspectionRemarks")
                                .HasMaxLength(500);

                            b1.Property<int>("InspectionResult");

                            b1.Property<int>("ItemNo");

                            b1.Property<string>("Model")
                                .HasMaxLength(200);

                            b1.Property<string>("PropertyClassHint")
                                .HasMaxLength(64);

                            b1.Property<decimal>("Quantity");

                            b1.Property<string>("SerialNo")
                                .HasMaxLength(200);

                            b1.Property<string>("StockPropertyNo");

                            b1.Property<string>("TechnicalSpecifications")
                                .HasMaxLength(1000);

                            b1.Property<string>("Unit")
                                .IsRequired()
                                .HasMaxLength(64);

                            b1.Property<decimal>("UnitCost");

                            b1.HasKey("AssetInspectionAcceptanceReportId", "__synthesizedOrdinal");

                            b1.ToTable("AssetIARs", "asset_procurement");

                            b1
                                .ToJson("LineItems")
                                .HasColumnType("jsonb");

                            b1.WithOwner()
                                .HasForeignKey("AssetInspectionAcceptanceReportId");
                        });

                    b.Navigation("LineItems");
                });

            modelBuilder.Entity("AMIS.Modules.AssetProcurement.Domain.AssetPurchaseOrders.AssetPurchaseOrder", b =>
                {
                    b.OwnsMany("AMIS.Modules.AssetProcurement.Domain.AssetPurchaseOrders.AssetPurchaseOrderLineItem", "LineItems", b1 =>
                        {
                            b1.Property<Guid>("AssetPurchaseOrderId");

                            b1.Property<int>("__synthesizedOrdinal")
                                .ValueGeneratedOnAdd();

                            b1.Property<string>("Brand")
                                .HasMaxLength(200);

                            b1.Property<string>("Description")
                                .IsRequired()
                                .HasMaxLength(500);

                            b1.Property<int>("ItemNo");

                            b1.Property<string>("Model")
                                .HasMaxLength(200);

                            b1.Property<string>("PropertyClassHint")
                                .HasMaxLength(64);

                            b1.Property<decimal>("Quantity");

                            b1.Property<string>("TechnicalSpecifications")
                                .HasMaxLength(1000);

                            b1.Property<string>("Unit")
                                .IsRequired()
                                .HasMaxLength(64);

                            b1.Property<decimal>("UnitCost");

                            b1.HasKey("AssetPurchaseOrderId", "__synthesizedOrdinal");

                            b1.ToTable("AssetPurchaseOrders", "asset_procurement");

                            b1
                                .ToJson("LineItems")
                                .HasColumnType("jsonb");

                            b1.WithOwner()
                                .HasForeignKey("AssetPurchaseOrderId");
                        });

                    b.Navigation("LineItems");
                });

            modelBuilder.Entity("AMIS.Modules.AssetProcurement.Domain.AssetPurchaseRequests.AssetPurchaseRequest", b =>
                {
                    b.OwnsMany("AMIS.Modules.AssetProcurement.Domain.AssetPurchaseRequests.AssetPurchaseRequestLineItem", "LineItems", b1 =>
                        {
                            b1.Property<Guid>("AssetPurchaseRequestId");

                            b1.Property<int>("__synthesizedOrdinal")
                                .ValueGeneratedOnAdd();

                            b1.Property<string>("Brand")
                                .HasMaxLength(200);

                            b1.Property<decimal>("EstimatedUnitCost");

                            b1.Property<string>("ItemDescription")
                                .IsRequired()
                                .HasMaxLength(500);

                            b1.Property<int>("ItemNo");

                            b1.Property<string>("Model")
                                .HasMaxLength(200);

                            b1.Property<string>("PropertyClassHint")
                                .HasMaxLength(64);

                            b1.Property<decimal>("Quantity");

                            b1.Property<string>("TechnicalSpecifications")
                                .HasMaxLength(1000);

                            b1.Property<string>("Unit")
                                .IsRequired()
                                .HasMaxLength(64);

                            b1.HasKey("AssetPurchaseRequestId", "__synthesizedOrdinal");

                            b1.ToTable("AssetPurchaseRequests", "asset_procurement");

                            b1
                                .ToJson("LineItems")
                                .HasColumnType("jsonb");

                            b1.WithOwner()
                                .HasForeignKey("AssetPurchaseRequestId");
                        });

                    b.Navigation("LineItems");
                });
#pragma warning restore 612, 618
        }
    }
}
